### ISSUE TITLE
gate does not find HunterGate.cmake

### ISSUE THREAD

**Issue by tastytea** [cpp-pm/hunter#56]
gate is looking for `HunterGate.cmake` in the root of the build dir, but it is in `_deps/setuphunter-src/cmake/HunterGate.cmake`.

* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **Yes**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and there is no solution to my problem there. **Yes**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **Yes**
* I've read [Reporting bugs section](https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs) carefully. **Yes**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in the example is the same as in [documentation](https://docs.hunter.sh/en/latest/packages.html). **Did not use them**
* I'm using [latest](https://github.com/cpp-pm/hunter/releases) Hunter `URL`/`SHA1`. **Yes**

* I've created [SSCCE](http://www.sscce.org/) reproducing the issue:
```cmake
# CMakeLists.txt
cmake_minimum_required(VERSION 3.14)

include(FetchContent)
FetchContent_Declare(SetupHunter GIT_REPOSITORY https://github.com/cpp-pm/gate)
FetchContent_MakeAvailable(SetupHunter)

project(foo)
add_executable(foo foo.cpp)
```

Here is the log until first error reported by Hunter, option `HUNTER_STATUS_DEBUG` is `ON`:
* [build.log](https://github.com/cpp-pm/hunter/files/3807950/build.log)

I've checked that the first error in logs **IS NOT** `external.build.failed`. **Yes**

* I'm building on Linux.
* I'm using system CMake
* CMake version: <3.14.6>

* I'm not using toolchain

I'm using the next command line on generate step:
```
cmake -DHUNTER_ENABLED=YES -DHUNTER_STATUS_DEBUG=ON
```

---

**Comment by bkotzz** [comment]
Related to https://github.com/cpp-pm/gate/pull/2

**Comment by bkotzz** [comment]
@tastytea can you verify that the issue is now fixed?

**Comment by tastytea** [comment]
I still get the same error with a clean build directory. I have verified that `_deps/setuphunter-src/CMakeLists.txt` is the same as <https://github.com/cpp-pm/gate/blob/master/CMakeLists.txt>.

I believe the error is in line 96: <https://github.com/cpp-pm/gate/blob/1bd3d7f42d2bad1edd47d89e141c3375ab267b02/CMakeLists.txt#L69>. Changing the path to `${CMAKE_CURRENT_LIST_DIR}/cmake/HunterGate.cmake` works for me.

**Comment by cristianadam** [comment]
@tastytea  thank you for testing!

**Comment by bkotzz** [comment]
Hopefully the last iteration - @tastytea let us know if you still see issues

**Comment by tastytea** [comment]
The issue is solved, thanks.
